즉시 판매 기능 구현
Team-BC-1/gream pull request #17
Opened 2024-01-07 16:56 UTC by Mayst1232

## 개요
판매 기능 중 즉시 판매 기능 구현 및 기능 테스트를 위한 임시 상품 추가
(추후 충돌 날 경우 반드시 이 엔티티를 삭제할 것)

## 작업사항
- 판매 엔티티 추가
- 판매 컨트롤러 추가
- 판매 서비스 추가
- 판매 레포지토리 추가
- 즉시 판매 서비스 성공 테스트 추가
- 임시 상품 엔티티 / 컨트롤러 / 서비스 / 레포지토리 추가

## 관련 이슈
- close #11

2024-01-07 18:14 UTC, Mayst1232 commented
죄송합니다 실수로 브랜치를 새로 안파고 그냥 냅다 만들어서 두개의 풀리가 합쳐졌습니다...ㅠㅠ

2024-01-08 06:10 UTC, vanillacake369 requested changes
고생하셨네요,,,,
저희 함께 화이팅해보아요,,,

2024-01-08 06:10 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/sell/dto/response/SellBidResponseDto.java
> +}
내용이 비어있는데 혹시 이유가 있을까요~?

2024-01-08 06:10 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/sell/dto/response/SellNowResponseDto.java
> +}
내용이 비어있는데 혹시 이유가 있을까요~? 22

2024-01-08 06:10 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/sell/entity/Gifticon.java
> +    public Gifticon(String gifticonImg, Sell sell) {
private으로 막아두시는 게 좋지 않을까 싶습니다!!

2024-01-08 06:10 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/sell/entity/Sell.java
> +    public Sell(Long price, Boolean isClose, LocalDateTime deadlineAt, Boolean isNow, String paymentType, User user, Product product) {
private 으로 생성자를 막아두는 게 좋다고 생각합니다~! 혹시 어떻게 생각하시나요~?

2024-01-08 06:10 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/sell/entity/Sell.java
> +    private String paymentType;
잘 가,,,고마웠어,,,

2024-01-08 06:10 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/sell/repository/SellRepository.java
> +public interface SellRepository {
extends JpaRepository로 해주세용~!~!

2024-01-08 06:10 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/sell/service/impl/SellServiceImpl.java
> +    }
나중에~~~~ ProductService로 의존해주시는 게 좋을 거 같아요!
이미 아실 거 같고, 임시로 짜신 거 같지만 혹시나 해서 언급해보아요~

2024-01-08 06:22 UTC, closed without merging