관리자 상품 생성 api
Team-BC-1/gream pull request #202
Opened 2024-01-26 13:06 UTC by Binsreoun

## 개요
관리자 상품 생성 api

## 작업사항
- 관리자 상품 controller 생성
- 상품 생성 requestDto 생성 
- 상품 생성 responseDto 생성 
- 상품 생성 서비스 생성 
- 상줌 중복 이름 에러 코드 생성 

## 관련 이슈
- close #201

2024-01-27 15:28 UTC, vanillacake369 reviewed
고생하셨습니다!

코멘트 한 번만 확인해주세요~~

2024-01-27 15:28 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/product/service/query/ProductService.java
> +    }
아래와 같이 리팩토링하면 메서드의 역할 분리를 할 수 있지 않을까요 ?? 🤗

```java
public void addProduct(AdminProductRequestDto adminProductRequestDto) {
    String productName = adminProductRequestDto.getName();
    
    if (productRepository.existsByName(productName)) {
        throw new GlobalException(ResultCase.DUPLICATED_PRODUCT_NAME);
    } 
    
    Product product = buildProductFromRequest(adminProductRequestDto);
    productRepository.save(product);
}

private Product buildProductFromRequest(AdminProductRequestDto adminProductRequestDto) {
    return Product.builder()
            .name(adminProductRequestDto.getName())
            .brand(adminProductRequestDto.getBrand())
            .description(adminProductRequestDto.getDescription())
            .imageUrl(adminProductRequestDto.getImageUrl())
            .price(adminProductRequestDto.getPrice())
            .build();
}

```

2024-01-27 16:54 UTC, vanillacake369 requested changes
하나 궁금한 게 있어서 남겨봅니당!

2024-01-27 16:54 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/admin/dto/AdminProductResponseDto.java
> +}
API 명세서 상에서 추가된 상품에 대한 값들을 반환하게끔 되어있는데요 !
혹시 이 부분은 필요없다고 판단하셔서 빼신 걸까요??

2024-01-28 04:11 UTC, Binsreoun commented on src/main/java/bc1/gream/domain/product/service/query/ProductService.java
> +    }
수정하겠습니당

2024-01-28 06:55 UTC, vanillacake369 submitted a review, later dismissed
🙇‍♂️🙆‍♂️👍

2024-01-30 02:56 UTC, lycoris62 approved these changes
좋습니다!!

2024-01-30 03:37 UTC, lycoris62 approved these changes
SGTM

2024-01-30 03:37 UTC, merged