관리자가 유저 환급 신청 승인 처리하는 기능 추가
Team-BC-1/gream pull request #212
Opened 2024-01-29 15:05 UTC by Mayst1232

## 개요
관리자가 유저 환급 신청 승인 처리하는 기능 추가

## 작업사항
- 관리자가 유저 환급 신청 승인 처리하는 기능 컨트롤러 API 추가
- 관리자가 유저 환급 신청 승인 처리하는 기능 서비스 API 추가

## 관련 이슈
- close #208

2024-01-29 21:15 UTC, vanillacake369 requested changes
고생하셨습니당! 코멘트 확인 부탁드려욥~

2024-01-29 21:15 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/admin/service/AdminService.java
> +    }
1. `checkUser` 라는 메서드명은 어떤 역할과 책임을 가지는지 파악하기가 힘든 것 같아요!

2. 해당 함수가 여러 역할과 책임을 가지고 있는 것 같습니다.
    a. loginId를 통한 User 조회
    b. user가 admin인지 검증, 아니라면 예외처리

3. admin에 대한 검증은, Security 단에서 AOP를 통해 검증하고 있으므로, 중복검증을 해줄 필요가 없다고 생각해요! 혹시 어떻게 생각하시나요?

4. Caller 측에서 User를 반환받아 사용하지 않는 것 같아요, 여기서 User를 다시 반환해줄 필요가 있을까 싶어요! 혹시 어떻게 생각하시나요?

2024-01-29 21:15 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/admin/controller/AdminController.java
> +    @DeleteMapping("/refund/{id}")
혹시 @Operation 을 통해서 Swagger Doc 달아주실 수 있으실까요??

@Operation(summary = "~~", description = "~~")

2024-01-30 00:40 UTC, lycoris62 requested changes
수고하셨습니다!

2024-01-30 00:40 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/admin/controller/AdminController.java
> +        AdminRefundPassResponseDto responseDto = adminService.refundPass(userDetails.getUser(), id);
소소해서 안 변경해도 되지만 메서드는 동사로 시작하는 것이 좋습니다!

2024-01-30 00:40 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/admin/service/AdminService.java
> +    }
위에서 지훈님이 말씀해주셨지만, 스프링 시큐리티 측에서 `/api/admin/**`로 들어오는 API는 `ROLE_ADMIN` 권한이 있어야 접근 가능하도록 해서 관리자 중 특정 누군가를 지정해야 하는 것이 아니니, 이 부분은 빼도될 것 같습니다.

2024-01-30 02:28 UTC, lycoris62 approved these changes
수고하셨습니다!

2024-01-30 02:28 UTC, vanillacake369 approved these changes
👍👍

2024-01-30 02:46 UTC, Binsreoun approved these changes

2024-01-30 03:29 UTC, vanillacake369 approved these changes
좋아요! Command , Query 가 잘 분리되었네요 ㅎㅎ

2024-01-30 03:29 UTC, merged