Refactor/set transactional to class levels
Team-BC-1/gream pull request #228
Opened 2024-02-02 02:04 UTC by vanillacake369

## 개요
내용을 적어주세요.

## 작업사항
- 내용을 적어주세요.

## 관련 이슈
-

2024-02-02 05:32 UTC, lycoris62 approved these changes
좋습니다!!

2024-02-02 05:36 UTC, Mayst1232 requested changes

2024-02-02 05:36 UTC, Mayst1232 commented on src/main/java/bc1/gream/domain/buy/service/command/BuyCommandService.java
>          return buy.getUser().getLoginId().equals(user.getLoginId());
요친구 여기만 쓰면 private으로 바꿉시다!

2024-02-03 08:19 UTC, Mayst1232 approved these changes

2024-02-03 08:21 UTC, merged