관리자 관련 기능 테스트 코드 추가
Team-BC-1/gream pull request #255
Opened 2024-02-06 09:29 UTC by Mayst1232

## 개요
관리자 관련 기능 테스트 코드 추가

## 작업사항
- 환급 관련 테스트 스텁 추가
- 관리자 컨트롤러 테스트 코드 추가

## 관련 이슈
- close #254

2024-02-06 23:42 UTC, vanillacake369 requested changes
고생하셨습니다! 

다만 Controller Test 목적성 관련해서 질문 드리고 싶은 부분이 있습니다~!

답볌 부탁드려욥!

2024-02-06 23:42 UTC, vanillacake369 commented on src/test/java/bc1/gream/domain/admin/controller/AdminControllerTest.java
> +    }
ControllerTest 는 주어진 요청에 대한 예측되는 결과를 뱉어주길 테스트하는 것이라고 생각합니다.

예측되는 ResponseDto를 지정해주어야 하지 않을까 생각합니다.

개인적으로 아래와 같이 구현했는데 해당 패턴을 사용하여 구현하시는 게 어떨까 싶습니다!
https://github.com/Team-BC-1/gream/blob/4a25d15e4fb55cb6ec35189cb07dcc2358134a0c/src/test/java/bc1/gream/domain/payment/toss/controller/TossPaymentControllerTest.java#L61-L97

2024-02-07 06:04 UTC, Mayst1232 commented on src/test/java/bc1/gream/domain/admin/controller/AdminControllerTest.java
> +    }
음 컨트롤러 테스트에서 결과적으로 status().isOk()와 code, message가 나오는걸로 기대하는 것이
충분하다고 생각을해서 작성하긴 했습니다..!
데이터 부분까지 추가하여 다시 작성하겠습니다..!

2024-02-07 06:11 UTC, Mayst1232 commented on src/test/java/bc1/gream/domain/admin/controller/AdminControllerTest.java
> +    }
다른 컨트롤러 두개는 response가 비어있는거라 추가하지 않았습니다..!

2024-02-07 06:12 UTC, lycoris62 approved these changes
수고하셨습니다!

2024-02-07 06:29 UTC, vanillacake369 approved these changes
고생하셨습니다!! 👍👍

2024-02-07 06:32 UTC, merged