판매입찰 / 구매입찰 내역 조회
Team-BC-1/gream pull request #42
Opened 2024-01-10 07:35 UTC by vanillacake369

## 개요
내용을 적어주세요.

## 작업사항
- 판매입찰 / 구매입찰 내역 조회 기능 구현

## 관련 이슈
- 

## 아래 관점으로 코드리뷰 부탁드려요~
### 로직
- QueryDsl 조회 시, 쿼리문이 제대로 구현되어있는가? ✅
- 검증 역할이 분리되어있는가? ✅
- 주문 / 구매 / 판매 에 따른 관심사 분리가 적절히 수행되어있는가? ✅
### 테스트
- 테스트 코드가 꼼꼼히 작성되어있는가 ✅
  - 서비스 단위 테스트에 어색한 부분이 없는가? ✅
  - 유닛 테스트에 어색한 부분이 없는가? ✅
### 코드 컨벤션
- 팀에서 규정지은 코드 컨벤션을 잘 지키고 있는가? ✅

2024-01-10 09:04 UTC, lycoris62 requested changes
수고하셨습니다!

2024-01-10 09:04 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
> +            .orElse(null);
이거 null 보단 빈 list 넣는 게 더 좋을 것 같아요! 그러면 자연스럽게 Optional 을 안 쓸 수 있게 되어 성능도 좋아질 것 같습니다.

2024-01-10 09:04 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/order/repository/SellRepositoryCustom.java
> +    Page<Sell> findAllPricesOf(Product product, Pageable pageable);
List 로 바꾸기로 했습니다!

2024-01-10 13:06 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/order/repository/SellRepositoryCustom.java
> +    Page<Sell> findAllPricesOf(Product product, Pageable pageable);
변경 완료 입니다!!!

2024-01-10 13:06 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/product/controller/ProductQueryController.java
> +            .orElse(null);
변경 완료 2222

2024-01-11 06:27 UTC, Mayst1232 approved these changes
수고많으셨습니다!!

2024-01-11 06:27 UTC, Binsreoun approved these changes
수고하셨습니다!

2024-01-11 06:29 UTC, lycoris62 approved these changes
수고하셨습니다!

2024-01-11 06:29 UTC, merged