상품 API 기능 구현
Team-BC-1/gream pull request #5
Opened 2024-01-07 10:52 UTC by vanillacake369

## 개요
엔티티/레포지토리
전체조회 API
상세조회 API

## 작업사항
- [x] 상품 엔티티 생성
- [x] 상품 레포지토리

- [ ] 상품 전체 조회 컨틀롤러 작성
- [ ] 상품 전체 조회 서비스 작성
- [ ] 상품 전체 조회 컨트롤러 테스트
- [ ] 상품 전체 조회 서비스 테스트

- [ ] 상품 상세 조회 컨틀롤러 작성
- [ ] 상품 상세 조회 서비스 작성
- [ ] 상품 상세 조회 컨트롤러 테스트
- [ ] 상품 상세 조회 서비스 테스트

## 관련 이슈
- close #4

2024-01-07 12:24 UTC, lycoris62 requested changes
리뷰 남깁니다~!

2024-01-07 12:24 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/product/entity/Product.java
> +@NoArgsConstructor
여기 `@NoArgsConstructor(access = AccessLevel.PROTECTED)` 로 변경하면 좋을 것 같습니다! 
그리고 `@Table(name = "tb_product")` 로 명시적으로 테이블명을 만들어주세요!

2024-01-07 12:24 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/product/entity/Product.java
> +@AllArgsConstructor(access = AccessLevel.PACKAGE)
혹시 내부 생성자로 `@Builder` 패턴을 쓰지 않고 `@AllArgsConstructor`를 쓴 이유가 있을까요??

2024-01-07 12:24 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/product/repository/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, Long> {
`JpaRepository` 를 상속받기 보다, 아래처럼 꼭 필요한 메서드만 정의하면 좋을 것 같습니다! 
```java
@RepositoryDefinition(domainClass = User.class, idClass = Long.class)
public interface UserRepository {

    User save(User user);

    Optional<User> findByLoginId(String loginId);

    boolean existsByLoginId(String loginId);

    boolean existsByNickname(String nickname);
}
```

2024-01-07 12:24 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/product/entity/Product.java
> +    @NotNull
`@NotNull` 은 요청 DTO 단에서 걸러지기도 하고, 또 `@Column` 의 속성 중 `nullable` 로도 할 수 있을 것 같습니다!

2024-01-07 13:42 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/product/entity/Product.java
> +    @NotNull
@Column에서 nullable=false를 제거해도, @NotNull이 붙어있으면 DDL 생성 시 not null로 생성되기 때문에 이렇게 작성했어요!
 혹시 nullable 처리 대신 @NotNull로 처리해도 무관할까요??
 
 https://www.baeldung.com/hibernate-notnull-vs-nullable
 
 @lycoris62

2024-01-07 13:44 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/product/repository/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, Long> {
옹! 처음 보는 코드인데 해당 코드로 기능제한 하면 이점이 어떤 게 있을까요?

2024-01-07 13:44 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/product/entity/Product.java
> +@AllArgsConstructor(access = AccessLevel.PACKAGE)
바아아로 수정 들어갔습니다! 😅 안일하게 작성했네요,,

2024-01-07 13:44 UTC, vanillacake369 commented on src/main/java/bc1/gream/domain/product/entity/Product.java
> +@NoArgsConstructor
네!! 저 코드 컨벤션이 아직 낯설어서 실수 했네여 ㅠ

2024-01-07 15:23 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/product/repository/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, Long> {
사용하지 않는 메서드는 생성되지 않고, 추가되는 메서드는 커밋에서 확인할 수 있어서 기존 프로젝트에서 좋았던 것 같은데 나중에 다시 의논해볼까요?

2024-01-07 15:35 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/product/entity/Product.java
> +    @NotNull
앗 그렇군요. 전 `@Column` 어노테이션을 사용해야 하는 상황에서 nullable까지 다룰 수 있어서 쓰긴 했는데요, 이건 그럼 의논을 해볼까요?

2024-01-07 16:03 UTC, lycoris62 requested changes
궁금한 점 적어두었습니다!!

2024-01-07 16:03 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/product/service/query/unit/ProductCondition.java
> +) {
혹시 BigInteger 쓰신 이유가 있을까요??

2024-01-07 16:03 UTC, lycoris62 commented on src/main/java/bc1/gream/domain/product/repository/ProductRepositoryCustomImpl.java
> +            .selectFrom(product)
혹시 `JPAQueryFactory queryFactory` 을 빈으로 등록해두셨는데 `QueryDslConfig` 을 주입받은 이유가 있을까요???

2024-01-08 01:23 UTC, Binsreoun approved these changes

2024-01-08 01:23 UTC, Binsreoun commented on src/main/java/bc1/gream/domain/product/controller/query/ProductQueryController.java
@RestController로 바꿔주세요!

2024-01-08 06:11 UTC, closed without merging